const i18n = {
  en: {
    translation: {
      'navbar': {
        'home': 'Home',
        'tutorial': 'Tutorial',
        'contact': 'Contact',
        'newMap': 'Create new map',
        'form': 'Meta',
        'map': 'Map',
        'preview': 'Preview',
        'exportAsPDF': 'as PDF',
        'exportAsSVG': 'as SVG',
        'exportAsPNG': 'as PNG',
        'login': 'Log in',
        'logout': 'Log out',
        'authorization': 'Authorization',
        'share': {
          'label': 'Share',
          'social': {
            link: 'Social networks',
            title: 'Share this map on a social media plattform',
            msg: 'Map for {{name}} on {{date}} in {{place}}\n\nPDF: {{-linkPDF}}',
          },
          'html': {
            link: 'Blog (HTML)',
            title: 'Embedd this map into your own website',
          }
        }
      },
      'home': {
        'headline': 'Maps for you political actions',
        'description': 'An Aktionskarte consists of of map extract where you can find important informations like a demo route or marked interesting places. These maps should help you and your comrades to locate yourself in an unkown area.',
        'mapListing': 'Below you can find already created public maps:',
      },
      'tutorial': {
        'headline': 'How can I create an Aktionskarte?',
      },
      'contact': {
        'headline': 'Mail',
        'introduction': 'You have comments, questions or want to contact us? Just write us an eamil',
        'preGPG': 'If possible then encrypt your mail. Our PGP key can be found <a href="{{gpgLink}}">here</a>  or just get it from a public key server.',
        'postGPG': 'You can as well download the key with your mail client. Pay attention that the <i>fingerprint</i> is the same as above.',
      },
      'remark': {
        'headline': 'Remark',
        'description': 'Aktionskarten is inspired by the work of <a href="https://aktionskarten.noblogs.org/">Kartographische Aktion</a>. They provide maps for example for demonstrations. Furthermore they wrote a tutorial how you can make maps on your own. Our idea was to simplify this further. The icon set which we use is from them.'
      },
      'sources': {
        'headline': 'Sources',
        'description': 'All components of Aktionskarten are open source. You can find them here:',
      },
      'form': {
        'createMap': 'Create new map',
        'editMapTitle': 'Edit map',
        'editMap': 'Save',
        'deleteMap': 'Delete map',
        'deleteText': 'Do you really want delete this map?',
        'cancel': 'Cancel',
        'saved': 'Saved',
        'name': {
          'label': 'Name',
          'placeholder': 'What is the name?',
          'description': 'The name will be displayed in the top left corner of your map.',
        },
        'place': {
          'label': 'Place',
          'placeholder': 'Where does it happen?',
          'description': 'A place is necessary because people need to know where your action takes place.'
        },
        'mapExtract': {
          'label': 'Map extract',
          'button':'Change map extract',
        },
        'date': {
          'label': 'Date',
          'placeholder': 'When does it happen?',
          'description': 'Will be rendered below the name of your map.'
        },
        'description': {
          'label': 'Description',
          'placeholder': 'Put here your call for action.',
          'description': 'It will be displayed on the backside of your map.'
        },
        'legend': {
          'label': 'Legend',
          'placeholderKey': 'Key',
          'placeholderValue': 'Value',
          'button': 'Add',
          'description': 'You can save here information in so called key-value pairs. This could be <i>Twitter-@account</i>, <i>EA-0891234</i> or <i>Hashtag-#B0803</i>. They will be rendered on your map.',
        },
        'modal': {
          'title': 'Map {{name}} has been created',
          'button': 'Select map extract',
          'preText': 'Just you and your friends should be able to edit the map. Therefor the following an autogenerated token has been created:',
          'postText': 'Only who knows this token can edit the map. Send this link to your comrades but leave out the token for the public.',
          'footer': 'Store the link or at least the passwort somewhere safely.'
        }
      }
    }
  },
  de: {
    translation: {
      'navbar': {
        'home': 'Überblick',
        'tutorial': 'Anleitung',
        'contact': 'Kontakt',
        'newMap': 'neue Karte erstellen',
        'form': 'Metadaten',
        'map': 'Kartenausschnitt',
        'preview': 'Vorschau',
        'exportAsPDF': 'als PDF',
        'exportAsSVG': 'als SVG',
        'exportAsPNG': 'als PNG',
        'login': 'Anmelden',
        'logout': 'Abmelden',
        'authorization': 'Authorisierung',
        'share': {
          'label': 'Teilen',
          'social': {
            link: 'Soziale Netzwerke',
            title: 'Teile diese Karte in einem Sozialen Netzwerk',
            msg: 'Aktionskarte für {{name}} am {{date}} in {{place}}\n\nPDF: {{-linkPDF}}',
          },
          'html': {
            link: 'Blog (HTML)',
            title: 'Binde diese Karte in deine eigene Website ein',
          }
        }
      },
      'home': {
        'headline': 'Karten für deine direkte Aktion',
        'description': 'Eine Aktionskarte besteht aus einem Kartenausschnitt, in dem wichtige Informationen wie eine Demoroute oder interessante Orte markiert sind. So eine Karte soll dir und deinen Mitstreiter*innen helfen, sich am Ort des Geschehens leichter zurechtzufinden.',
        'mapListing': 'Im Folgenden findest bereits erstellte öffentliche Karten:'
      },
      'tutorial': {
        'headline': 'Wie erstelle ich eine Aktionskarte?',
      },
      'contact': {
        'headline': 'Mail',
        'introduction': 'Ihr habt Anmerkungen, Fragen oder wollt mit uns in Kontakt treten? Schreibt uns einfach eine Mail',
        'preGPG': 'Wenn möglich dann am besten verschlüsselt. Unser PGP Schlüssel findet ihr <a href="{{gpgLink}}">hier</a> oder ladet ihn von einem öffentlichen Schlüsselserver runter.',
        'postGPG': 'Ihr könnt ihn natürlich auch über euren Mailclient runterladen. Achtet dabei dass der <i>Fingerprint</i> dem obigen entspricht.',
      },
      'remark': {
        'headline': 'Anmerkungen',
        'description': 'Aktionskarten basiert auf Ideen und Arbeit von <a href="https://aktionskarten.noblogs.org/">Kartographische Aktion</a>. Sie stellen Karten zum Beispiel für Demonstrationen zur Verfügung und haben auch eine Anleitung verfasst wie du selbst solche Karten erstellen kannst. Unsere Idee war dies noch weiter zu vereinfachen. Die von uns verwendeten Bilder der Marker sind u.a. von ihnen.'
      },
      'sources': {
        'headline': 'Quelltexte',
        'description': 'All Komponenten von Aktionskarten sind freie Software. Du kannst sie hier finden:'
      },
      'form': {
        'createMap': 'Neue Aktionskarte erstellen',
        'editMapTitle': 'Karte bearbeiten',
        'editMap': 'Speichern',
        'deleteMap': 'Karte löschen',
        'deleteText': 'Willst du wirklich diese Karte löschen?',
        'cancel': 'Abbrechen',
        'saved': 'Gespeichert',
        'name': {
          'label': 'Name',
          'placeholder': 'Name der Aktion',
          'description': 'Der Name wird als Überschrift oben links auf deiner Aktionskarte sein.',
        },
        'place': {
          'label': 'Ort',
          'placeholder': 'Ort der Aktion',
          'description': 'Ein Ort ist notwendig damit die Leute wo deine Aktion stattfindet. Er wird auch auf der Karte unter dem Namen erscheinen.',
        },
        'mapExtract': {
          'label': 'Kartenausschnitt',
          'button': 'Kartenausschnitt ändern',
        },
        'date': {
          'label': 'Date',
          'placeholder': 'Wann findet es statt?',
          'description': 'Datum und Zeit werden unter der Überschrift auf der Karte erscheinen',
        },
        'description': {
          'label': 'Beschreibung',
          'placeholder': 'Pack hier deinen Aufruf rein. Er wird auf der Rückseite zum Beispiel beim PDF-Export auf der Rückseite der Aktionskarte erscheinen.'
        },
        'legend': {
          'label': 'Legende',
          'placeholderKey': 'Schlüssel',
          'placeholderValue': 'Wert',
          'button': 'Hinzufügen',
          'description': 'Hier gespeicherte Schlüssel-Werte-Paare sollen dir ermöglichen wichtige Informationen zu hinterlegen. Beispiele sind <i>Twitter-@account</i>, <i>EA-0891234</i> oder <i>Hashtag-#B0803</i>. Diese werden dann auf deiner Aktionskarte hinterlegt.',
        },
        'modal': {
          'title': 'Karte {{name}} wurde erstellt',
          'button': 'Kartenausschnitt auswählen',
          'preText': 'Damit nur du und deine Freunde die Karte bearbeiten können gibt es ein zufallgeneriertes Passwort:',
          'postText': 'Nur wer im Besitz des Passworts ist kann die Karte bearbeiten. Deinen Mitstreiter*innen schickst du somit den kompletten Link. Dem Rest nur den den Teil ohne Passwort.',
          'footer': 'Speicher dir das Passwort oder den Link gut ab.',
        }
      },

      // Error messages from backend
      'Map already exists. Use another name!': 'Karte existiert bereits. Wähle einen anderen Namen!'
    },
  },
}

export default i18n
