const i18n = {
  en: {
    translation: {
      'navbar': {
        'newMap': 'Create new map',
        'map': 'Map',
        'exportAsPDF': 'as PDF',
        'exportAsSVG': 'as SVG',
        'exportAsPNG': 'as PNG',
        'login': 'Log in',
        'logout': 'Log out',
        'authorization': 'Authorization',
        'share': {
          'label': 'Share',
          'social': 'Social networks',
          'html': 'Blog (HTML)'
        }
      },
      'home': {
        'headline': 'Maps for you political actions',
        'description': 'An Aktionskarte consists of of map extract where you can find important informations like a demo route or marked interesting places. These maps should help you and your comrades to locate yourself in an unkown area.',
        'mapListing': 'Below you can find already created public maps:',
      },
      'form': {
        'createMap': 'Create new map',
        'editMap': 'Edit map',
        'name': {
          'label': 'Name',
          'placeholder': 'What is the name?',
          'description': 'The name will be displayed in the top left corner of your map.',
        },
        'place': {
          'label': 'Place',
          'placeholder': 'Where does it happen?',
          'description': 'A place is necessary because people need to know where your action takes place.'
        },
        'mapExtract': {
          'label': 'Map extract',
          'button':'Change map extract',
        },
        'date': {
          'label': 'Date',
          'placeholder': 'When does it happen?',
          'description': 'Will be rendered below the name of your map.'
        },
        'description': {
          'label': 'Description',
          'placeholder': 'Put here your call for action.',
          'description': 'It will be displayed on the backside of your map.'
        },
        'legend': {
          'label': 'Legend',
          'placeholderKey': 'Key',
          'placeholderValue': 'Value',
          'button': 'Add',
          'description': 'You can save here information in so called key-value pairs. This could be <i>Twitter-@account</i>, <i>EA-0891234</i> or <i>Hashtag-#B0803</i>. They will be rendered on your map.',
        },
        'modal': {
          'title': 'Map {{name}} has been created',
          'button': 'Select map extract',
          'preText': 'Just you and your friends should be able to edit the map. Therefor the following an autogenerated token has been created:',
          'postText': 'Only who knows this token can edit the map. Send this link to your comrades but leave out the token for the public.'
        }
      }
    }
  },
  de: {
    translation: {
      'navbar': {
        'newMap': 'neue Karte erstellen',
        'map': 'Karte',
        'exportAsPDF': 'als PDF',
        'exportAsSVG': 'als SVG',
        'exportAsPNG': 'als PNG',
        'login': 'Anmelden',
        'logout': 'Abmelden',
        'authorization': 'Authorisierung',
        'share': {
          'label': 'Teilen',
          'social': 'Soziale Netzwerke',
          'html': 'Blog (HTML)'
        }
      },
      'home': {
        'headline': 'neue Karte erstellen',
        'description': 'Eine Aktionskarte besteht aus einem Kartenausschnitt in dem wichtige Informationen wie eine Demoroute oder interessante Orte markiert sind. So eine Karte soll dir und deinen Mitstreiter*innen helfen sich am Ort des Geschehens leichter zurechtzufinden.',
        'mapListing': 'Im folgenden findest bereits erstellte öffentliche Karten:'
      },
      'form': {
        'createMap': 'Neue Aktionskarte erstellen',
        'editMap': 'Karte bearbeiten',
        'name': {
          'label': 'Name',
          'placeholder': 'Wie heißt es?',
          'description': 'Der Name wird als Überschrift oben links auf deiner Aktionskarte sein.',
        },
        'place': {
          'label': 'Ort',
          'placeholder': 'Wo findet es statt?',
          'description': 'Ein Ort ist notwendig damit die Leute wo deine Aktion stattfindet. Er wird auch auf der Karte unter dem Namen erscheinen.',
        },
        'mapExtract': {
          'label': 'Kartenausschnitt',
          'button': 'Kartenausschnitt ändern',
        },
        'date': {
          'label': 'Date',
          'placeholder': 'Wann findet es statt?',
          'description': 'Datum und Zeit werden unter der Überschrift auf der Karte erscheinen',
        },
        'description': {
          'label': 'Beschreibung',
          'placeholder': 'Pack hier deinen Aufruf rein. Er wird auf der Rückseite zum Beispiel beim PDF-Export auf der Rückseite der Aktionskarte erscheinen.'
        },
        'legend': {
          'label': 'Legende',
          'placeholderKey': 'Schlüssel',
          'placeholderValue': 'Wert',
          'button': 'Hinzufügen',
          'description': 'Hier gespeicherte Schlüssel-Werte-Paare sollen dir ermöglichen wichtige Informationen zu hinterlegen. Beispiele sind <i>Twitter-@account</i>, <i>EA-0891234</i> oder <i>Hashtag-#B0803</i>. Diese werden dann auf deiner Aktionskarte hinterlegt.',
        },
        'modal': {
          'title': 'Karte {name} wurde erstellt',
          'button': 'Kartenausschnitt auswählen',
          'preText': 'Damit nur du und deine Freunde die Karte bearbeiten können gibt es ein zufallgeneriertes Passwort:',
          'postText': 'Nur wer im Besitz des Passworts ist kann die Karte bearbeiten. Deinen Mitstreiter*innen schickst du somit den kompletten Link. Dem Rest nur den den Teil ohne Passwort',
        }
      }
    },
  },
}

export default i18n
